apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner-controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: controller
          image: github-actions-runner-controller
          imagePullPolicy: Never
