namespace: default

resources:
  - crd/github-actions-runner.kaidotdev.github.io_runners.yaml
  # +kubebuilder:scaffold:crdkustomizeresource
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - config_map.yaml
  - deployment.yaml
  - pod_disruption_budget.yaml
  - role.yaml
  - role_binding.yaml
  - service.yaml
  - service_account.yaml
  - stateful_set.yaml

configurations:
  - kustomizeconfig.yaml

vars:
  - name: SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: registry
    fieldref:
      fieldpath: metadata.name
  - name: CONFIGMAP_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: metadata
    fieldref:
      fieldpath: metadata.name
