apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-runner-controller-leader-election
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-runner-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - registry
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - metadata
    verbs:
      - patch
