apiVersion: v1
kind: Service
metadata:
  name: github-actions-runner-controller-registry
spec:
  type: NodePort
  selector:
    app: github-actions-runner-controller-registry
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
