nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - path: spec/tokenSecretKeyRef/name
        group: github-actions-runner.kaidotdev.github.io
        version: v1
        kind: Runner